JuliaGPU/CUDAnative.jl

src/array.jl

This allows us to get more of the Array semantics like `pointer(A)` and `pointer(A, i)`

Define unsage_convert for CuDeviceArray.

---

examples/oob.jl
examples/reduce/benchmark.jl
examples/reduce/verify.jl
src/device/intrinsics.jl
test/examples.jl
test/runtests.jl

Also add functionality to run the examples during package testing.
Fixes #35.

Fix the at-cuprintf example.

---

test/runtests.jl

This is pretty embarrassing. Anyway, fixes #33. ~~Based on #37 for now.~~

Remove stray return from quote block.

---

src/device/array.jl
test/execution.jl

0.6 syntax deprecation fixes

---

.travis.yml
REQUIRE
docs/src/index.md
src/CUDAnative.jl
src/jit.jl
src/reflection.jl
test/documentation.jl
test/runtests.jl
test/util.jl

Ref JuliaGPU/CUDAdrv.jl#49 and maleadt/LLVM.jl#33

Support for loading/testing the package if the build failed.

---

src/execution.jl
test/perf/launch_overhead/cuda.jl

Fine-grained recompilation of dependent kernels.

---

deps/build.jl
src/reflection.jl

Discover cuobjdump.

---

REQUIRE
deps/build.jl
src/CUDAnative.jl
src/jit.jl

Try to avoid some duplication between CUDAdrv/CUDArt/CUDAnative. Only used for build and logging, but we could put other shared functionality there too.

Introduce CUDAapi

---

src/jit.jl

Requires JuliaLang/julia#22517, fixes #74.

Use Julia's set of optimization passes

---

src/cgutils.jl
src/device/intrinsics/warp_shuffle.jl
test/intrinsics.jl

Probably useful for @MikeInnes and/or @SimonDanisch (to support more element types for your arrays).

WIP: Make shuffle work for arbitrarily-sized Reals

---

src/device/intrinsics/memory_shared.jl
src/pointer.jl
test/codegen.jl

Ref https://github.com/JuliaLang/julia/pull/23367

Adapt to new anonymous pointers in Julia.

---

src/device/array.jl
test/array.jl

to make `for elem in A::CuDeviceArray` work!

overload iteration protocol

---

deps/build.jl

Warn against using Julia 0.6.1

---

REQUIRE
examples/peakflops.jl
src/CUDAnative.jl
src/device/intrinsics/memory_shared.jl
src/jit.jl
src/pointer.jl
src/reflection.jl
test/intrinsics.jl
test/pointer.jl
test/util.jl

Needs some work on Compat to get it to like all forms of `@nospecialize`

Fix 0.7 deprecations.

---

REQUIRE
deps/build.jl
src/CUDAnative.jl
src/device/intrinsics/synchronization.jl
src/device/intrinsics/warp_shuffle.jl
src/jit.jl
src/reflection.jl

Better driver/toolkit version handling

---

src/jit.jl
src/reflection.jl

Fix and simplify JIT interactions (Base<->CUDAnative).

---

REQUIRE
src/device/array.jl
test/execution.jl

Use CUDAdrv's new buffer type

---

test/array.jl
test/execution.jl
test/intrinsics.jl
test/util.jl

Preparing for CUDAdrv.CuArray removal.

Don't use CUDAdrv.CuArray for testing

---

test/intrinsics.jl

Pretty easy. Together with JuliaGPU/CUDAapi.jl#10, we apparently fully support Windows :-)

Fixes for Windows.

---

deps/build.jl

Address https://github.com/JuliaGPU/CUDAapi.jl/issues/27
Summarized, this:
- removes the CUDA 9.0 / PTX ISA 6.0 requirement warning: although it is undocumented, I would assume PTX code < ISA 6.0 to work as expected on Volta hardware with CUDA 9.0 (ie. not requiring synchronizing shuffle, or explicit warp sync barriers)
- relaxes the driver/toolkit version checks, but makes it an error when it fails
I'm hesitant to make the latter an error, but seeing how I ran into an actual incompatibility with CuArrays.jl (see https://github.com/JuliaGPU/CUDAapi.jl/issues/27) I don't think we should allow otherwise.

Fix the various version compatibility checks.

---

src/jit.jl

Maintain custom globalUnique counter for kernel naming.

---

REQUIRE
docs/src/man/usage.md
examples/hello_world.jl
examples/oob.jl
examples/pairwise.jl
examples/peakflops.jl
examples/reduce/reduce.jl
examples/scan.jl
examples/vadd.jl
src/CUDAnative.jl
src/device/intrinsics/memory_shared.jl
src/execution.jl
src/jit.jl
src/reflection.jl
src/utils.jl
test/array.jl
test/base.jl
test/codegen.jl
test/execution.jl
test/intrinsics.jl
test/perf/launch_overhead/cudanative.jl
test/util.jl

Fixes #94
Requires https://github.com/JuliaGPU/CUDAdrv.jl/pull/88

Use keyword arguments for at-cuda.

---

src/irvalidation.jl

let me know if you want a more fine tuned solution ;)

windows uses the exe extension

---

src/irvalidation.jl

[release-0.6] Fix detection of libjulia on Windows

---

src/CUDAnative.jl
src/init.jl
src/reflection.jl
test/runtests.jl

Fix #159. Alternative to `CUDA_VISIBLE_DEVICES`.
cc @MikeInnes @ViralBShah

Implement device switching.

---

examples/hello_world.jl
examples/oob.jl
examples/pairwise.jl
examples/peakflops.jl
examples/reduce/reduce.jl
examples/scan.jl
examples/vadd.jl
src/execution.jl
src/jit.jl
src/reflection.jl
test/base.jl
test/codegen.jl
test/device/array.jl
test/device/execution.jl
test/device/intrinsics.jl
test/perf/launch_overhead/cudanative.jl
test/util.jl

WIP: Ignore return value of kernels

---

REQUIRE
deps/build.jl
src/CUDAnative.jl
src/jit.jl

https://github.com/JuliaGPU/CUDAdrv.jl/pull/100#issuecomment-379448363

[release-0.6] Fixes for CUDAapi

---

.gitlab-ci.yml
README.md
docs/make.jl
test/REQUIRE
test/documentation.jl
test/runtests.jl

See https://github.com/JuliaGPU/gitlab-ci

Enable GitLab CI/CD.

---

examples/hello_world.jl

fixed different formatting string for windows in example

---

src/compiler.jl

NVPTX specifies it, see NVPTXTargetMachine::computeDataLayout.

Don't hard-code the data layout.

---

src/pointer.jl
test/codegen.jl
test/device/pointer.jl

~TODO: don't add TBAA for the unknown/generic address spaces.~

RFC/WIP: Add TBAA information to optimize loads from different address spaces.

---

src/compiler.jl
test/codegen.jl

Use Base.fullname

---

src/device/intrinsics/output.jl
test/device/intrinsics.jl

Fix printf argument promotion

---

src/pointer.jl
test/device/pointer.jl

Fix pointer recursion when indexing.

---

src/compiler/validation.jl
test/codegen.jl

Catch ccalls in the validator.

---

src/device/intrinsics/warp_shuffle.jl
src/device/pointer.jl
test/device/pointer.jl

Don't test ldg below sm_32.

---

src/CUDAnative.jl
src/deprecated.jl
src/device/array.jl
src/execution.jl

Ref https://github.com/JuliaGPU/CuArrays.jl/pull/167#discussion_r228058712

Reintroduce cudaconvert shorthand for calling Adapt.

---

test/device/execution.jl

Test https://github.com/JuliaGPU/CUDAnative.jl/issues/274

Test kwargs.

---

test/codegen.jl

Just putting it out here when we have an upstream fix.
ref https://github.com/JuliaLang/julia/issues/29952

Add a test for #278.

---

test/base.jl

Fix test on master branch.

---

src/execution.jl
test/device/execution.jl

Fix https://github.com/JuliaGPU/CUDAnative.jl/issues/297

Recompile kernel if captured values change

---

.gitlab-ci.yml
deps/build.jl
docs/Project.toml
docs/make.jl
src/execution.jl
test/runtests.jl

Simplify documentation generation

---

test/examples.jl
test/util.jl

Pass along --project with julia_cmd()

---

REQUIRE
test/device/array.jl

Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/313

Revert upstream SubArray bounds checking change

---

.gitlab-ci.yml
src/device/runtime_intrinsics.jl

Also some CI changes.
bors try

Generate all box/unbox functions

---

src/compiler/irgen.jl

Modularize irgen.

---

src/compiler/irgen.jl
src/device/runtime_intrinsics.jl
test/device/execution.jl

Fix https://github.com/JuliaGPU/CUDAnative.jl/issues/329
bors r+

Lower throw and friends in an LLVM pass.

---

examples/scan.jl

http://http.developer.nvidia.com/GPUGems3/gpugems3_ch39.html ->
https://developer.nvidia.com/gpugems/GPUGems3/gpugems3_ch39.html

updated URL to correct URL for scan.jl example

---

REQUIRE
docs/make.jl
src/device/cuda_intrinsics/memory_shared.jl
src/device/pointer.jl
src/execution.jl
test/device/array.jl
test/device/codegen.jl
test/device/execution.jl
test/device/pointer.jl
test/pointer.jl
test/runtests.jl
test/util.jl

https://github.com/JuliaGPU/CUDAdrv.jl/pull/125

WIP: Adapt to the new CUDAdrv.CuPtr pointer type.

---

src/compiler/irgen.jl

It's been a while since we had one of these.
Build will still fail due to https://github.com/JuliaLang/julia/pull/31083
bors try

Fix deprecation warning.

---

src/reflection.jl

Don't pass invalid default values to code_... arguments.

---

src/device/cuda_intrinsics/synchronization.jl
test/device/intrinsics.jl

Added the following three intrinsics in `src\device\cuda_intrinsics\synchronization.jl`:
- `sync_threads_count(pred)` for LLVM IR `llvm.nvvm.barrier0.popc(i32)`;
- `sync_threads_and(pred)` for `llvm.nvvm.barrier0.and(i32)`;
- `sync_threads_or(pred)` for `llvm.nvvm.barrier0.or(i32)`.
and corresponding tests in `test\device\intrinsics.jl`.
_Although this is simple, I would like to express my special thanks of gratitude to Valentin Churavy and Tim Besard._

Add Synchronisation Barriers (count, and, or)

---

src/compiler/irgen.jl
test/codegen.jl

skip verifier if requested

---

src/compiler/validation.jl
test/codegen.jl

@dpsanders mentioned recently that it is sometimes non-trivial to see why a certain argument is not isbits.
This tries to recursively walk the tree to see if we can give a better explanation.

explain why an argument is not isbits

---

src/compiler/driver.jl
test/codegen.jl

Thanks to @vtjnash
Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/359 https://github.com/JuliaGPU/CUDAnative.jl/issues/265

Detect unbound typevars.

---

src/device/runtime.jl
test/codegen.jl

Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/387

Add runtime functions to box floating point values.

---

src/compiler/driver.jl
src/compiler/rtlib.jl
src/init.jl
src/reflection.jl
test/codegen.jl
test/device/codegen.jl
test/device/cuda.jl

For testing on non-CUDA CI, etc.

Fix running without CUDA

---

src/device/cuda/math.jl
test/device/cuda.jl

ref: https://github.com/JuliaGPU/CuArrays.jl/pull/325

pow function for exponet is Int64

---

src/compiler/irgen.jl

We use the multiply-defined functions to reconstruct backtrace information at compile time.

Don't cache modules when compiling in debug mode.

---

CITATION.bib
README.md
docs/src/index.md

Compared to the original BibTeX entry, I also added the information about the preprint on arXiv

[skip ci] Add CITATION.bib

---

Project.toml
src/CUDAnative.jl
src/compiler/common.jl

excise Pkg dependency

---

src/compiler/driver.jl

Greatly reduces register pressure for some of the heaviest kernels in Oceananigans.jl.
Thanks @maxpkatz for the hint.

Don't unconditionally link and trigger rdc compilation.

---

.gitlab-ci.yml
Project.toml
src/compiler.jl
src/compiler/irgen.jl
src/compiler/optim.jl

Support DI for LLVM8

---

src/device/cuda/output.jl
test/codegen.jl
test/device/cuda.jl
test/device/execution.jl

Just a temporary improvement, we should really work towards getting `show(::IO, x)` to work.
Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/19

Add a wrapper for at-cuprintf.

---

src/compiler/rtlib.jl

Fix https://github.com/JuliaGPU/CUDAnative.jl/issues/451
ref https://github.com/JuliaLang/julia/pull/32651

Fix compilecache-like functionality on 1.4

---

src/device/cuda/math.jl

#430 
This may not be the way we want to do this, and I'm open to alternatives, but as I see it this is an effective solution.
If we want a more full set of operations to match those for real values, I can add those as well--just not sure how far we want to go.

Add some more complex operations

---

src/CUDAnative.jl
test/runtests.jl

Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/497#issuecomment-560075768

Implement toolkit version getter.

---

src/reflection.jl

This PR adds a `verbose` option to `@device_code_sass` and friends, which prints code generation statistics such as number of used registers, used constant memory, register spilling, ...
Example:
```julia
julia> function kernel()
return
end
kernel (generic function with 1 method)
julia> @device_code_sass @cuda kernel()
.headerflags	@"EF_CUDA_TEXMODE_UNIFIED EF_CUDA_64BIT_ADDRESS EF_CUDA_SM75 EF_CUDA_VIRTUAL_SM(EF_CUDA_SM75)"
.elftype	@"ET_EXEC"
//--------------------- .text.ptxcall_kernel_2    --------------------------
.section	.text.ptxcall_kernel_2,"ax",@progbits
.sectioninfo	@"SHI_REGISTERS=4"
.align	128
.global         ptxcall_kernel_2
.type           ptxcall_kernel_2,@function
.size           ptxcall_kernel_2,(.L_12 - ptxcall_kernel_2)
.other …
```

Add verbose option to code_sass

---

src/init.jl

Prevent stack overflow during init, and use preexisting device.

---

src/device/cuda/math.jl

Fixes https://github.com/JuliaGPU/CuArrays.jl/issues/543
Make complex exp type stable

fix CuArrays.jl #543 - complex exp type instability

---

src/compiler/validation.jl

Fixes (the original issue from) #408, works around JuliaLang/julia#33347.

Limit deptch of nonisbits-explanation tree and work around Julia issue.

---

src/compiler/irgen.jl
src/device/cuda/memory_shared.jl
src/utils.jl
test/device/codegen.jl

~TODO: lift the safe_fn functionality~

gensym the shmem id.

---

src/device/cuda/atomics.jl
test/device/cuda.jl

Amend https://github.com/JuliaGPU/CUDAnative.jl/pull/532 (which didn't have "push from maintainers" enabled).

Implement atomic_cas!

---

src/CUDAnative.jl
src/compiler/irgen.jl

Disable all debug info for LLVM 8.0+

---

src/compiler/common.jl
src/compiler/driver.jl
src/compiler/irgen.jl
src/utils.jl
test/codegen.jl

Implements https://github.com/JuliaGPU/CUDAnative.jl/issues/556
@vchuravy not that horrific, right? I mean, the generated names are, but it seems worth it:

Mangle names like C++ does.

---

src/bindeps.jl
src/compatibility.jl
src/compiler/driver.jl
src/compiler/irgen.jl
src/execution.jl

Now that CI is enabling debug output for all jobs...

Improve debug output.

---

src/compiler/irgen.jl

Fixes https://github.com/JuliaGPU/CuArrays.jl/issues/442

Whitelist hypot from method substitution warning.

---

docs/src/device/wmma.md
src/device/cuda/wmma.jl
test/device/wmma.jl

Closes #548 
Depends on https://github.com/JuliaLang/julia/pull/34760

Use AddrSpacePtr to call WMMA intrinsics

---

src/device/pointer.jl
test/codegen.jl

Ref https://github.com/JuliaLang/julia/issues/34865

Avoid calling reinterpret(Nothing, nothing).

---

src/compiler/debug.jl

This surfaced on the norecursion branch, where we can't do the hacky thing anymore where we compiled a unique function body for every call in order to get perfectly reconstructible backtraces.

Eagerly prune empty debug info during backtrace construction.

---

Manifest.toml
src/CUDAnative.jl
src/bindeps.jl
src/compatibility.jl
src/compiler.jl
src/compiler/rtlib.jl
src/cupti/libcupti.jl
src/execution.jl
src/init.jl
src/nvtx/libnvtx.jl
src/reflection.jl
test/device/cuda.jl
test/runtests.jl

Alternative to https://github.com/JuliaGPU/CUDAnative.jl/pull/590

Defer initializing deps to actual run time.

---

src/execution.jl

https://github.com/JuliaLang/julia/pull/34973

Remove workaround.

---

src/reflection.jl

Resolves https://github.com/JuliaGPU/CUDAnative.jl/issues/563

Better error on CUPTI insufficient permissions.

---

.gitlab-ci.yml
examples/wmma/high-level.jl
examples/wmma/low-level.jl
test/device/wmma.jl
test/util.jl

Disables WMMA tests on debug until https://github.com/JuliaGPU/CUDAnative.jl/issues/587 is resolved.

Bump CI to 1.4, and include debug build

---

examples/wmma/high-level.jl
examples/wmma/low-level.jl
src/device/cuda/wmma.jl
test/device/wmma.jl

Closes #587 
Depends on https://github.com/JuliaLang/julia/pull/34996 (though it will still work with older Julia)

Fix return type of WMMA intrinsics

---

src/device/array.jl

Fixes https://github.com/JuliaGPU/CuArrays.jl/issues/677

Make sure array intrinsics propagate inboundness.

---

src/device/cuda/output.jl
test/device/cuda.jl

add @cushow macro
