- README.md
Adding Base.Test to example code allows macro @test to be found
> Add "using Base.Test"

- src/CUDAnative.jl
- src/device/array.jl
- src/execution.jl
- src/types.jl
Generated functions are fragile, and we were doing stuff we shouldn't (calling overloaded functions and calling its methods after the generated function was defined). This broke the package if precompilation was disabled, but even with precompilation enabled the generated function behind `@cuda` threw errors because during first inference-time execution `cudaconvert(DevicePtr{T})` wasn't defined. This also slowed down the kernel launch sequence.
Ref JuliaLang/julia#19942
> Replace cudaconvert with simple pure funtion.

- src/device/intrinsics.jl
- src/execution.jl
Counterpart to JuliaGPU/CUDAdrv.jl#15. Much less impressive savings, but simplifies the generated functions and results in cleaner generated code.
> Reduce launch overhead

- src/device/array.jl
- src/device/intrinsics.jl
- test/array.jl
- test/runtests.jl
- allow more styles of constructors (some typevars, all typevars, etc), mimicking Base.Array
- allow calling outer constructors with dims<:Integer
- improve tests
- docs
Also convert some unrelated methods to 0.6-style where.
cc @cfoket
> Improve CuDeviceArray constructors.

- src/CUDAnative.jl
- src/jit.jl
This patch passes `--nvptx-fma-level=1` to LLVM's NVPTX backend to mimic the default behavior of `nvcc` with respect to the generation of FMA instructions. Note that `nvcc`'s `--fmad` option defaults to `true`.
> Enable generation of FMA instructions.

- REQUIRE
at least since the new type syntax has been used, the package wouldn't work
on early 0.6.0-dev versions so shouldn't claim to support them any more
> make minimum julia version 0.6.0-pre

- src/device/intrinsics.jl
Julia 0.7 will add a location node to captured macro names, causing invalid IR.
> Use string for symbol name

- test/base.jl
- test/codegen.jl
- test/execution.jl
- test/runtests.jl
Hopefully fixes #53. cc @keno @vchuravy
> Use a value sink to prevent noinline functions from getting optimized away.

- src/execution.jl
- src/jit.jl
- test/execution.jl
```
_       _ _(_)_     |  A fresh approach to technical computing
(_)     | (_) (_)    |  Documentation: https://docs.julialang.org
_ _   _| |_  __ _   |  Type "?help" for help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 0.6.0-rc2.0 (2017-05-18 02:31 UTC)
_/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-unknown-linux-gnu
julia> using CUDAdrv, CUDAnative
julia> dev = CuDevice(0)
CUDAdrv.CuDevice(0, 0)
julia> ctx = CuContext(dev)
CUDAdrv.CuContext(Ptr{Void} @0x0000000000fa9520, true, true)
julia> foo() = @cuprintf("old")
foo (generic function with 1 method)
julia> @cuda (1,1) foo(); synchronize()
old
julia> foo() = @cuprintf("new")
foo (generic function with 1 method)
julia> @cuda (1,1) foo(); synchronize()
new
```
Needs test. Better way would be to have an inferable …
> Automatic recompilation of dependent kernels.

- docs/src/man/usage.md
- examples/hello_world.jl
- examples/oob.jl
- examples/pairwise.jl
- examples/reduce/benchmark.jl
- examples/reduce/verify.jl
- examples/scan.jl
- examples/vadd.jl
- src/CUDAnative.jl
- test/perf/launch_overhead/cuda.jl
- test/perf/launch_overhead/cudanative.jl
- test/perf/launch_overhead/cudanative_profile.jl
Simplifies code quite a bit. Mimics what CUDA does.
Maybe we should tie into the primary context business though, but then everyone's GC/refcount logic has to be aware of one another for it to work properly. Didn't really feel like doing that today. People should just use explicit contexts if they want to have control over resources, I guess.
> Use a default, global context for the first device.

- REQUIRE
- docs/src/man/performance.md
- examples/pairwise.jl
- src/execution.jl
- src/jit.jl
- src/reflection.jl
- test/codegen.jl
- test/execution.jl
Alternative to parametrizing the calling convention through eg. `CodegenParams`, idea from @vtjnash.
Depends on new version of LLVM.jl for maleadt/LLVM.jl#36
> Use kernel wrapper functions to improve argument passing

- src/device/array.jl
- src/device/intrinsics/memory_shared.jl
- src/device/util.jl
After #82, shared memory is aligned according to the datatype alignment rules. At the same time, the documentation for `cuMemAlloc` states `[the] allocated memory is suitably aligned for any kind of variable`. But some online sources state a 256-byte alignment from old documentation (`Any address of a variable residing in global memory or returned by one of the memory allocation routines from the driver or runtime API is always aligned to at least 256 bytes`), others seem to refer `textureAlignment`, while the PTX documentation for global loads states `[global] memory instructions support reading or writing words of size equal to 1, 2, 4, 8, or 16 bytes`...
So I'm not sure whether this is correct. Running our testsuite under `cuda-memcheck` now.
> Align memory accesses according to the datatype.

- REQUIRE
- docs/src/lib/compilation.md
- src/CUDAnative.jl
- src/cgutils.jl
- src/device/array.jl
- src/device/intrinsics/memory_shared.jl
- src/execution.jl
- src/pointer.jl
- src/reflection.jl
- test/array.jl
- test/codegen.jl
- test/execution.jl
- test/pointer.jl
- test/runtests.jl
This PR refactors a core part of CUDAnative: how pointers are represented, and how they are accessed. It introduces a `DevicePtr` struct (`Ptr` + AS) with (WIP) intrinsics for accessing memory, specialized on the address space. The type is used in `CuDeviceArray`, making `getindex` faster for global loads (which LLVM couldn't figure out).
fixes #79
> Add DevicePtr parameterized on address space

- src/CUDAnative.jl
- src/cgutils.jl
- src/execution.jl
- src/jit.jl
- src/reflection.jl
- test/codegen.jl
- test/execution.jl
Could improve performance of compiler (parse less IR) and generated code (internalizing functions allows LLVM to ignore calling conventions).
> Random LLVM-related improvements

- deps/build.jl
- src/jit.jl
The libdevice binaries have been consolidated into a single binary that works for
all the supported GPU architectures.
> Compatibility with CUDA 9.0

- src/execution.jl
- test/execution.jl
It's pretty common to pass a variable number of arrays through a tuple, so this would be pretty useful.
> cudaconvert for tuples

- src/pointer.jl
This makes it possible for LLVM to elide threadidx+1 -> unsafe_load(i-1).
eg. `vadd`, before:
```
.visible .entry ptxcall_add__61688(
.param .align 8 .b8 ptxcall_add__61688_param_0[16],
.param .align 8 .b8 ptxcall_add__61688_param_1[16],
.param .align 8 .b8 ptxcall_add__61688_param_2[16]
)
{
.reg .f32       %f<4>;
.reg .s32       %r<4>;
.reg .s64       %rd<14>;
ld.param.u64    %rd1, [ptxcall_add__61688_param_0+8];
ld.param.u64    %rd2, [ptxcall_add__61688_param_1+8];
ld.param.u64    %rd3, [ptxcall_add__61688_param_2+8];
mov.u32 %r2, %tid.x;
.loc 1 5 0
add.s32         %r3, %r2, 1;
mul.wide.u32    %rd4, %r3, 4;
add.s64         %rd5, %rd1, %rd4;
add.s64         %rd6, %rd5, -4;
cvta.to.global.u64      %rd7, %rd6;
ld.global.f32   %f1, [%rd7];
add.s64         %rd8, %rd2, %rd4;
add.s64 …
```
> Calculate i-1 using the type of the index.

- REQUIRE
- src/CUDAnative.jl
- src/irvalidation.jl
- src/jit.jl
Instead of refusing to emit, check compatibility afterwards.
> IR validation

- deps/build.jl
- examples/pairwise.jl
- examples/peakflops.jl
- examples/reduce/benchmark.jl
- examples/reduce/verify.jl
- examples/scan.jl
- examples/vadd.jl
- src/CUDAnative.jl
- src/device/intrinsics/synchronization.jl
- src/device/intrinsics/warp_shuffle.jl
- src/jit.jl
- test/execution.jl
- test/intrinsics.jl
- test/runtests.jl
Required on Volta, where threads can diverge within the warp. Blocked on NVPTX supporting PTX v6.0.
Probably also needs changes to the warp vote intrinsics.
> WIP: cooperative groups

- deps/build.jl
- src/CUDAnative.jl
Downgrade the selected version based on what nvcc and libcuda report.
This should prevent eg. passing too new PTX to ptxas. However, it might
still break eg. when compiling a too new libdevice with an older driver,
so we still warn at build-time.
> Cope better with CUDA driver/toolkit mismatches.

- docs/src/lib/reflection.md
- src/jit.jl
- src/reflection.jl
- test/codegen.jl
- test/codegen_device.jl
- test/execution.jl
This PR changes device code reflection to make it consistent and improve user friendliness.
Before, we extended `Base.code_*` and corresponding macro's, which was:
- inconsistent, because depending on how it was (mis)used, it could return CPU or GPU code (eg. `CUDAnative.@code_llvm` stuck in front of a proper GPU function call vs. broadcasting over a `CuArray`)
- limited, as it the macros really only could be used in front of `@cuda` calls
- annoying, because you need to specify whether you want to use Base or CUDAnative reflection
What I've tried in this PR:
- still have `code_` functions for generating code from known device method calls, but without extending Base
- remove the `@code_` macros, and replace them with `@device_code` macros that are guaranteed to always return device code …
> Rework device code reflection.

- src/jit.jl
cc @vchuravy 
Not going to merge this immediately, first want to benchmark on eg. Rodinia.
> Early-inline all functions into the entry.

- deps/build.jl
- src/reflection.jl
cc @SimonDanisch 
At this point, if we were to ship `libdevice` we wouldn't even require the CUDA toolkit at all, just the driver. But then we'd be required to prompt the EULA, etc, so I don't think I'll bother with that.
> Don't require ptxas or cuobjdump.

- TODO.md
- docs/src/lib/device/array.md
- src/cgutils.jl
- src/device/array.jl
- src/device/intrinsics/memory_shared.jl
- src/device/intrinsics/output.jl
- src/device/intrinsics/warp_shuffle.jl
- src/pointer.jl
- test/array.jl
- test/codegen.jl
- test/pointer_device.jl
- test/runtests.jl
This branch packs a couple of improvements, as well as initial support for `__ldg` for loading values through the texture cache. See the CUDA docs for more info, but in short: the texture cache is faster than the global cache (which caches global values automatically), but it is a non-coherent cache which implies that the array should be read-only for the entire duration of the kernel.
This PR only features the compiler support, no real front-end yet. Ideas/suggestions? Keyword argument to `getindex`? Constness typevar for CuArray/CuDeviceArray? Even though we'd need proper alias analysis (ref JuliaLang/julia#25890), this should already be usable in eg. non-mutating `broadcast`.
cc @vchuravy @MikeInnes
> Support for loading values through the texture cache (__ldg)

- src/jit.jl
- src/reflection.jl
- test/array.jl
- test/codegen.jl
`contains(haystack, needle)` is deprecated, use `occursin(needle, haystack)` instead.
`String(io::GenericIOBuffer)` is deprecated, use `String(take!(copy(io)))` instead.
`Base.STDOUT` is deprecated, use `stdout` instead
> Fix deprecation warnings

- src/execution.jl
- src/jit.jl
- test/codegen.jl
- test/execution.jl
Implements #163. Seems kinda insane.
```
_       _ _(_)_     |  A fresh approach to technical computing
(_)     | (_) (_)    |  Documentation: https://docs.julialang.org
_ _   _| |_  __ _   |  Type "?help" for help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 0.7.0-DEV.4473 (2018-03-06 05:55 UTC)
_/ |\__'_|_|_|\__'_|  |  Commit 2f826b55d6* (10 days old master)
|__/                   |  x86_64-unknown-linux-gnu
julia> using CUDAnative, CUDAdrv
julia> @device_code_llvm @cuda ((T, i)->(@cuprintf("Got %ld\n", unsafe_trunc(T, i)); return))(Int, 1.)
define void @ptxcall__6_1(%jl_value_t addrspace(10)*, double) local_unnamed_addr {
entry:
%args.i.i = alloca %vprintf_args, align 8
%2 = fptosi double %1 to i64, !dbg !5
%3 = bitcast %vprintf_args* %args.i.i to i8*, !dbg !11
call void …
```
> Support for passing non-isbits values, as long as they are unused.

- examples/scan.jl
@dpsanders and I needed `accumulate!` for Vectors today and we
run into the issue that the ammount of shmem requested depends on
`cols * rows`, wheras the kernel only needs `2 * rows`
> make scan example work for Vector

- src/device/intrinsics/indexing.jl
- test/device/intrinsics.jl
ref https://github.com/JuliaGPU/CUDAnative.jl/pull/149#issuecomment-360989609 (cc @vchuravy)
requires https://github.com/JuliaLang/julia/pull/26844 for the metadata to survive
Not sure if LLVM uses this, but heck why not at least provide the information.
With contextual dispatch, we can make it even more accurate (ie. device-specific).
> Attach range metadata to indexing intrinsics.

- examples/reduce/reduce.jl
- src/device/array.jl
- src/device/intrinsics/indexing.jl
- src/device/intrinsics/warp_shuffle.jl
- src/pointer.jl
- test/device/intrinsics.jl
Trial balloon, use Int instead of (U)Int32. We had been careful in order to preserve 32-bit precision of intrinsics, but sadly Julia is pretty bad at this and even trivial arithmetic immediately promotes to Int64.
Using Int simplifies stuff. As an additional advantage, the signedness and wider range of Int apparently allows for some better optimization by LLVM, but I'm not sure how that compares to the increased register pressure and eager `zext`s.
There's a kink though, because shuffle intrinsics require Int32 inputs, causing a inexactness check. Not sure how to deal with this.
> Use Int instead of 32-bit integers

- NEWS.md
- src/compiler.jl
- src/execution.jl
- src/init.jl
- src/validation.jl
- test/codegen.jl
- test/device/execution.jl
- test/util.jl
Detect calls of base intrinsics (#27):
```
julia> foo(i) = sin(i)
foo (generic function with 1 method)
julia> @cuda foo(1)
┌ Warning: calls to Base intrinsics might be GPU incompatible
│   exception =
│    You called sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:30, maybe you intended to call sin(x::Float64) in CUDAnative at /home/tbesard/Julia/CUDAnative/src/device/libdevice.jl:12 instead?
│    Stacktrace:
│     [1] sin at special/trig.jl:30
│     [2] foo at REPL[6]:1
└ @ CUDAnative compiler.jl:172
```
Detect recursive codegen (#122):
```
julia> @noinline foo(i) = i<0 ? i : bar(i)
foo (generic function with 1 method)
julia> @noinline bar(i) = i<0 ? i : foo(i)
bar (generic function with 1 method)
julia> @cuda foo(1)
ERROR: GPU compilation failed, try …
```
> Improve error reporting

- src/compiler.jl
- src/reflection.jl
Hides the annoying `.loc` instructions.
> Make PTX output verbose, but strip debug metadata.

- src/compiler.jl
- test/device/codegen.jl
- test/runtests.jl
We violate its assumption when rewriting the kernel entrypoint.
> Strip invariant.load from input pointers.

- src/compiler.jl
- src/reflection.jl
- src/validation.jl
- test/codegen.jl
Hurts performance a little, but keeps us from violating the semantics of Julia's non-IPO safe metadata.
> Don't inline if we don't need to.

- Project.toml
- examples/blackscholes.jl
- examples/hello_world.jl
- examples/multigpu.jl
- examples/oob.jl
- examples/pairwise.jl
- examples/peakflops.jl
- examples/reduce/reduce.jl
- examples/scan.jl
- examples/vadd.jl
- src/CUDAnative.jl
- src/compiler/common.jl
- src/compiler/driver.jl
- src/compiler/irgen.jl
- src/compiler/optim.jl
- src/compiler/validation.jl
- src/execution.jl
- src/reflection.jl
- test/codegen.jl
- test/device/array.jl
- test/device/codegen.jl
- test/device/execution.jl
- test/device/intrinsics.jl
- test/device/pointer.jl
- test/perf/launch_overhead/cudanative.jl
- test/util.jl
This is a breaking change, requiring a `return [nothing]` at the end of every kernel again.
> Remove kernel wrapper

- src/compiler/irgen.jl
- test/codegen.jl
Can as well keep on piling up hacks onto the exception rewriting.
Really wanting to remove it all and switch to Cassette overdubbing of `Core.throw`.
```
julia> broadcast(val->trunc(UInt,val), CuArray([1.1]))
1-element CuArray{UInt64,1}:
0x0000000000000001
julia> broadcast(val->trunc(UInt,val), CuArray([-1.]))
1-element CuArray{UInt64,1}:
ERROR: an unknown exception occurred
0x0000000000000000
```
> Remove unused arguments to demoted exceptions

- .gitlab-ci.yml
The documentation has links to `github.com/github.com/JuliaGPU/CUDAnative.jl.git/.../..`, which are broken.
Changing `TRAVIS_REPO_SLUG` fixes the links. Remotely related to https://github.com/JuliaDocs/Documenter.jl/pull/837
> Fix broken links in documetation

- src/execution.jl
Slightly reduces number of allocations that happen as part of `@cuda` (@andreasnoack noticed how there really shouldn't be any). According to `--track-allocation=user` the only allocations left are in `hash(ctx.handle::Ptr{Void}, h)`, but that really doesn't explain the other ~20 allocations that are reported by `@time`. Not sure how to proceed efficiently here, as I don't feel like debugging GC for this.
> Prevent tuple construction in kernel launch code.

- deps/build.jl
- src/reflection.jl
`nvdisasm` provides more information by default, as an example function calls are resolved to the symbol instead of the pointer, and has a couple of useful options.
This defaults to printing available line information and only printing the code and not the data section.
The other options that are useful are:
- `--print-life-ranges`: Printing life ranges for registers
- `--output-control-flow-graph`: Get a CFG of the kernels
> use nvdisasm instead of cuobjdump

- docs/make.jl
- docs/src/lib/compilation.md
- docs/src/lib/profiling.md
- docs/src/lib/reflection.md
- docs/src/man/performance.md
- src/execution.jl
I'm finally converting from old CUDArt to the newer infrastructure. I noticed a few places where I could help by improving the documentation. Now the only warnings when you include `make.jl` are related to `@ref`s to things like `InteractiveUtils.@code_llvm`, which AFAICT Documenter does not support.
The least satisfying part of this is the fact that I changed the "attachment point" for the documentation for `(::Kernel)(args...; kwargs...)`. The former choice was the most logical, but with a minute or two of experimentation I was unable to find a way to obtain that docstring from within the REPL. Consequently I moved it to the type itself, so that it can be obtained with `?CUDAnative.Kernel`.
> Various improvements to docs

- .gitignore
- src/execution.jl
Arguably a bit cleaner and removes a FIXME.
> Use `local` instead of explicit call to `gensym`

- src/init.jl
The version happens during precompilation, and might consequently cause context
creation in the parent process to fail when eg. using process exclusive mode.
> Don't initialize CUDA when querying for the version.

- src/compiler/common.jl
- src/compiler/driver.jl
- src/compiler/irgen.jl
- src/compiler/mcgen.jl
- src/compiler/optim.jl
- src/compiler/rtlib.jl
- src/device/runtime_intrinsics.jl
- src/reflection.jl
- test/codegen.jl
- test/device/array.jl
Implements `jl_box_uint64` which makes it possible to execute the following without our hacky `replace_throw!` pass:
```julia
function foo(i, ptr)
for Ri_base in 0:1:i
unsafe_store!(ptr, 0)
end
nothing
end
```
( this constructs a lot of boxes when creating exception objects )
Should also make it possible to eg. store into `CuArray{Any}` vectors, although it's pretty unclear there who owns that memory.
Additional difficulty: type tag values change across Julia sessions, so to avoid rebuilding the CUDAnative runtime each time I emit calls to `late_jl_uint64_type` and resolve those to actual values when linking the library.
> Implement heap-allocated boxes

- src/device/runtime_intrinsics.jl
Addresses https://github.com/JuliaGPU/CUDAnative.jl/issues/340
Crashes on `-g2` with the following MWE though:
```
using CUDAnative, StaticArrays
function knl!()
r_a = MArray{Tuple{4}, Float32}(undef)
for k in 1:4
@inbounds r_a[k] = 0
end
nothing
end
@cuda threads=(5, 5) blocks=4000 knl!()
using CUDAdrv
CUDAdrv.synchronize()
```
> Check for OOM when doing malloc.

- src/compiler/irgen.jl
- test/codegen.jl
`safe_fn` did not correctly mangle function names containing `^` due to a regex bug.
Found with @vchuravy.
> Fix safe_fn

- src/compiler/optim.jl
- test/codegen.jl
Fix https://github.com/JuliaGPU/CUDAnative.jl/issues/340
Depends on https://github.com/JuliaLang/julia/pull/31101
> Don't eagerly lower intrinsics.

- .gitlab-ci.yml
- src/init.jl
Seems like parts of CUDA (specifically, its libraries as seen in https://github.com/JuliaGPU/CuArrays.jl/pull/294) depend on there being a proper _primary_ context.
> Use the primary context instead of creating our own.

- Project.toml
- src/CUDAnative.jl
- src/compiler.jl
- src/compiler/driver.jl
- src/compiler/irgen.jl
- src/compiler/rtlib.jl
- src/reflection.jl
- test/codegen.jl
- test/runtests.jl
https://github.com/JuliaGPU/CUDAnative.jl/issues/354
```
[ Info: Testing using device GeForce GTX TITAN
────────────────────────────────────────────────────────
Time          
──────────────────────
Tot / % measured:               109s / 11.6%    
Section                   ncalls     time   %tot     avg
────────────────────────────────────────────────────────
LLVM IR generation           250    5.95s  47.3%  23.8ms
Julia IR generation          256    2.90s  23.1%  11.3ms
CUDA object generation       170    2.52s  20.0%  14.8ms
PTX assembly generation      210    1.20s  9.57%  5.72ms
────────────────────────────────────────────────────────
Test Summary: | Pass  Total
CUDAnative    |  279    279
```
Seems reasonable.
> Add some timer outputs.

- src/init.jl
- test/runtests.jl
~TODO: make the compilecache `device => ...` (we only really support a single context in CUDAnative) and wipe that.~
> Support for resetting the device.

- src/device/cuda/cooperative_groups.jl
- src/device/cuda/dynamic_parallelism.jl
- src/execution.jl
Avoid construction at run-time; fixes #376.
> llvmcall tuple arguments need to be a literal.

- examples/reduce/benchmark.jl
- examples/reduce/reduce.cu
- examples/reduce/reduce.jl
- src/device/array.jl
- src/device/cuda.jl
- src/device/cuda/atomics.jl
- src/device/pointer.jl
- test/device/cuda.jl
Still needs test, integration with CuDeviceArray (do we need an Atomic type like Base?), API matching with Base and CUDA, etc.
```julia
julia> using CUDAnative: DevicePtr
julia> code_llvm(CUDAnative.atomic_inc!, (DevicePtr{Int32,AS.Shared}, Int32))
define i32 @"julia_atomic_inc!_12382"(i64, i32) {
top:
%2 = call i32 @llvm.nvvm.atomic.load.inc.32.p3i32(i64 %0, i32 %1)
ret i32 %2
}
julia> code_llvm(CUDAnative.atomic_max!, (DevicePtr{UInt,AS.Generic}, UInt))
define i64 @"julia_atomic_max!_12417"(i64, i64) {
top:
%2 = inttoptr i64 %0 to i64*
%3 = atomicrmw umax i64* %2, i64 %1 acq_rel
ret i64 %3
}
julia> code_llvm(CUDAnative.atomic_add!, (DevicePtr{Int,AS.Generic}, Int))
define i64 @"julia_atomic_add!_12456"(i64, i64) {
top:
%2 = inttoptr i64 %0 to i64*
%3 = atomicrmw add i64* %2, i64 %1 …
```
> Support atomics

- src/compiler/validation.jl
- test/codegen.jl
Fix https://github.com/JuliaGPU/CUDAnative.jl/issues/384
Fix https://github.com/JuliaGPU/CUDAnative.jl/issues/361
```julia
julia> @cuda kernel()
ERROR: InvalidIRError: compiling kernel() resulted in invalid LLVM IR
Reason: unsupported use of an undefined name (use of 'undefined')
Stacktrace:
[1] kernel at REPL[64]:1
julia> kernel() = (BoundsError(1); return)
kernel (generic function with 3 methods)
julia> @cuda kernel()
ERROR: InvalidIRError: compiling kernel() resulted in invalid LLVM IR
Reason: unsupported dynamic function call (call to BoundsError(a) in Core at boot.jl:240)
Stacktrace:
[1] kernel at REPL[66]:1
```
> Better errors for delayed bindings and dynamic calls

- src/compiler/irgen.jl
Tries to fix #383 by maintaining our own compilation cache. Doesn't enable recursion, but should prevent us from generating ridiculously large LLVM modules. Won't be necessary post https://github.com/JuliaLang/julia/pull/25984.
```julia
julia> using CUDAnative
julia> function kernel(a, b)
a[1] = 2
b[1] = 3
nothing
end
kernel (generic function with 1 method)
julia> CUDAnative.code_llvm(kernel, NTuple{2,CuDeviceArray{Int,1,AS.Global}}; dump_module=true)
```
```llvm
; ModuleID = 'kernel'
source_filename = "kernel"
target triple = "nvptx64-nvidia-cuda"
%printf_args = type { i64 }
@exception = private unnamed_addr constant [10 x i8] c"exception\00"
@0 = private unnamed_addr constant [108 x i8] c"ERROR: a %s was thrown during kernel execution.\0A       Run Julia on debug level 2 for device …
```
> Partially cached compilation

- src/reflection.jl
Makes `@device_code_typed` slightly more useful since now one can relate
back quirks to actual line information
> default to debuginfo for typed code

- src/compiler/common.jl
- src/compiler/irgen.jl
- src/reflection.jl
- test/codegen.jl
- test/device/execution.jl
attempt at fixing #412 the example now leads to:
```
┌ Warning: Possible ABI missmatch                                                                                                                                                                                                     
│   name = "japi1_print_to_string_16521"                                                                                                                                                                                              
└ @ CUDAnative ~/.julia/dev/CUDAnative/src/compiler/irgen.jl:70                                                                                                                                                                       
┌ Warning: Possible ABI missmatch …
```
> relax ABI check

- src/CUDAnative.jl
- src/compiler/irgen.jl
Fixes #428
https://github.com/JuliaGPU/CUDAnative.jl/pull/436 got auto closed..
@vchuravy do we need the other cgparam as well?
> Use the new cgparam for LLVM 8.0 compatibility.

- docs/Project.toml
- src/device/cuda/output.jl
- src/execution.jl
You can do interpolation into docstrings, so it would currently show up as `@cuprint "Hello, World 42\n"` in the manual, which would, I'd argue, defeats the purpose of the example :slightly_smiling_face:
> Escape $ in docstrings

- test/device/cuda.jl
Avoids running out of resources on certain platforms. Fixes #444.
> Reduce number of threads used during shmem tests.

- .gitattributes
After this, I get:
```
% github-linguist --breakdown
100.00% Julia
Julia:
src/CUDAnative.jl
src/compiler.jl
src/compiler/common.jl
src/compiler/debug.jl
src/compiler/driver.jl
src/compiler/irgen.jl
src/compiler/mcgen.jl
src/compiler/optim.jl
src/compiler/rtlib.jl
src/compiler/validation.jl
src/deprecated.jl
src/device/array.jl
src/device/cuda.jl
src/device/cuda/assertion.jl
src/device/cuda/atomics.jl
src/device/cuda/cooperative_groups.jl
src/device/cuda/dynamic_parallelism.jl
src/device/cuda/indexing.jl
src/device/cuda/math.jl
src/device/cuda/memory_dynamic.jl
src/device/cuda/memory_shared.jl
src/device/cuda/misc.jl
src/device/cuda/output.jl
src/device/cuda/synchronization.jl
src/device/cuda/warp_shuffle.jl
src/device/cuda/warp_vote.jl
src/device/llvm.jl
src/device/pointer.jl …
```
> [skip ci] Ignore CITATION.bib and test/perf for language count

- src/device/cuda/warp_shuffle.jl
- test/device/cuda.jl
Use LLVM intrinsics, and have `shfl_idx` use 1-based indexing.
> Improvements to shfl

- src/device/cuda/atomics.jl
- test/device/cuda.jl
- test/util.jl
This PR aims to handle various errors encountered by `@atomic` and report them nicely
Fixes #453
> Making @atomic robust

- Manifest.toml
- src/CUDAnative.jl
- src/compiler/driver.jl
- src/compiler/irgen.jl
- src/device/runtime.jl
- src/exceptions.jl
- src/execution.jl
- src/init.jl
- test/device/execution.jl
This is a promising change, making it possible to throw exceptions without killing the GPU:
```julia
julia> @cuda ((a)->(a[2]=1;return))(CuArray([1]))
julia> ERROR: a exception was thrown during kernel execution.
Run Julia on debug level 2 for device stack traces.
julia> 
julia> synchronize()
ERROR: KernelException: exception thrown during kernel execution on device Quadro RTX 5000
Stacktrace:
[1] check_exceptions() at /home/tim/Julia/pkg/CUDAnative/src/exceptions.jl:50
[2] check_exception_hook(::Symbol) at /home/tim/Julia/pkg/CUDAnative/src/exceptions.jl:60
[3] macro expansion at /home/tim/Julia/pkg/CUDAdrv/src/error.jl:94 [inlined]
[4] cuCtxSynchronize() at /home/tim/Julia/pkg/CUDAdrv/src/libcuda.jl:156
[5] synchronize() at /home/tim/Julia/pkg/CUDAdrv/src/context.jl:185
[6] top-level …
```
> Use a module exception flag instead of trapping the GPU.

- src/reflection.jl
This makes it easier to diff two directories.
> Use a local unique identifier when dumping code to disk.

- .gitlab-ci.yml
- src/CUDAnative.jl
- silence load-time warnings, as the environment flag didn't always work
- use a module flag to indicate success
- allow global usage
> Initialization improvements

- src/execution.jl
This gets rid of some allocations and make the result inferrable
> use map instead of broadcast

- test/util.jl
> Pass additional arguments that aren't captured by julia_cmd().

- src/device/cuda/memory_shared.jl
Old versions of GPUArrays invoke `_shmem` with an integer id; make sure those are unique to pass `ptxas`.
Fixes issue introduced by https://github.com/JuliaGPU/CUDAnative.jl/pull/533
> Fix compatibility with older GPUArrays.

- src/reflection.jl
- test/codegen.jl
- test/device/cuda.jl
Integrate with Base's IR printer:
```llvm
julia> a = CuArray([1])
1-element CuArray{Int64,1,Nothing}:
1
julia> @device_code_llvm a .= 2
define void @ptxcall_anonymous27_27({ [1 x i64], i64 }, { [1 x i64], [1 x { i64 }] }) local_unnamed_addr {
entry:
%2 = alloca { [1 x { i64 }] }, align 8
%3 = alloca [1 x i64], align 8
%.fca.0.0.extract1 = extractvalue { [1 x i64], i64 } %0, 0, 0
%4 = bitcast { [1 x { i64 }] }* %2 to i8*
call void @llvm.lifetime.start.p0i8(i64 8, i8* %4)
%5 = bitcast [1 x i64]* %3 to i8*
call void @llvm.lifetime.start.p0i8(i64 8, i8* %5)
;  @ /home/tim/Julia/pkg/GPUArrays/src/host/broadcast.jl:59 within `#27'
; ┌ @ /home/tim/Julia/pkg/GPUArrays/src/device/indexing.jl:50 within `macro expansion'
; │┌ @ /home/tim/Julia/pkg/GPUArrays/src/device/indexing.jl:28 within …
```
> Use the Julia LLVM IR printer to support the debuginfo argument.

- src/compiler/driver.jl
- src/compiler/irgen.jl
- src/compiler/optim.jl
- test/device/execution.jl
The unoptimised llvm module is currently the one produced by Julia, I find it quite helpful to also look at the one that we produce after turning it into a gpu kernel.
> Make the kernel transform mandatory

- src/compiler/irgen.jl
- src/compiler/optim.jl
- src/compiler/rtlib.jl
- test/codegen.jl
This works around its inability to deal with Julia's operand bundles.
Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/553
> Run the inliner at the end of the pipeline.

- test/examples.jl
The test suite involves spinning up new julia instances, but these can end up loading the users startup.jl which is undesirable.
> use --startup=no in spawned tests

- src/execution.jl
- test/device/execution.jl
Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/459 by setting `ci.edges` (from https://github.com/JuliaLang/julia/pull/32237) AND adding a fake call, both seem required to fool Julia.
This regresses launch performance, which I plan to look into soon.
> Fix method invalidation

- .gitlab-ci.yml
- src/compiler/irgen.jl
- test/codegen.jl
- test/device/execution.jl
Don't use a separate ptxcall naming scheme, as kernels are the only functions that get C++ mangled.
Also removes copying the debug info subprogram to the kernel wrapper, since that's apparently invalid: https://reviews.llvm.org/D32975. Ideally we'd create a distinct subprogram here, but the C API doesn't expose that functionality.
> Simplify naming of wrapper kernels.

- src/compiler/common.jl
- src/reflection.jl
device_code macros can capture multiple kernels, so prefix with the compiler job when outputting. also useful to capture what is being executed now that the (previously much too verbose) debug print of compiled kernels is gone.
> Print compilation job details when doing reflection.

- Manifest.toml
- src/CUDAnative.jl
- src/cupti/error.jl
- src/device/cuda/synchronization.jl
- src/exceptions.jl
- src/init.jl
- src/reflection.jl
- test/runtests.jl
This PR makes CUDAnative aware of Julia's task execution model, and generalizes the initialization code (which now was only aware of threads, and the fact that each thread can independently switch contexts as far as CUDA is concerned) to take tasks into account. This makes it possible to have each task work with a different device, seamlessly switching contexts when execution switches from one task to another. The code should also work in the case tasks migrate between threads.
```
julia> using CUDAnative, CUDAdrv
julia> device!(0)
julia> @info "Task $(current_task()) on thread $(Threads.threadid()) is working on device $(device())"
[ Info: Task Task (runnable) @0x00007f8ad533b820 on thread 1 is working on device CuDevice(0): GeForce RTX 2080 Ti
julia> @async begin
device!(1)
@info "Task …
```
> Support for Julia's multitasking.

- src/device/cuda.jl
- src/device/cuda/memory_shared.jl
- src/device/cuda/wmma.jl
- src/device/pointer.jl
- test/device/cuda.jl
- test/device/wmma.jl
- test/runtests.jl
This PR changes how we work with and store address-space pointers: instead of casting them to and from generic pointers, directly work with their in-address space representation. That means we don't have to `addrspacecast` anymore, just `inttoptr ... addrspace(...)*` directly.
For WMMA, this requires 1.5's Base.AddrSpacePtr, because otherwise we select intrinsics for the generic case which leads to illegal memory accesses (cc @thomasfaingnaert).
Fixes https://github.com/JuliaGPU/CUDAnative.jl/issues/641.
> Avoid address space casts.
